delete from xt_monitor;
delete from xt_monitor_cpu;
delete from xt_monitor_mem;
delete from xt_operate_logs;
delete from xt_login_logs;
delete from xt_quartz_log;
delete from xt_error_logs;
delete from xt_loadinfo;
delete from xt_start_stop_log;